version: '3.8'
services:
  api:
    container_name: another-knowelege
    build:
      context: .
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 3007:3007
    environment:
      DB_HOST: postgres
      POSTGRES_USERNAME: andy
      POSTGRES_PASSWORD: localdbpass
      POSTGRES_DATABASE: knowelege-base
      DB_PORT: 55013
    volumes:
      - ./:/usr/src/app/

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=andy
      - POSTGRES_PASSWORD=localdbpass
      - POSTGRES_DB=knowelege-base
      - PGPORT=55013
    ports:
      - "55013:55013"
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql

